name: Publish container

on:
  workflow_dispatch:
  release:
    types: released

jobs:
  build:
    name: Publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine docker tags
        id: version_tags
        shell: python
        run: |
          import os
          import re
          from pathlib import Path

          gh_output = Path(os.getenv("GITHUB_OUTPUT", ""))

          if "${{ github.event_name }}" == "workflow_dispatch":
              with gh_output.open("a", encoding="utf8") as f:
                  f.writelines(["tags=test"])

          else:
              dockerfile_txt = Path("Dockerfile").read_text()

              match = re.search(r"/cxx-(?P<sonar_cxx_version>\d+\.\d+\.\d+)/", dockerfile_txt)

              if match is None:
                  raise ValueError("Unable not determine sonar-cxx version.")

              with gh_output.open("a", encoding="utf8") as f:
                  f.writelines([f"tags=latest,{match.group('sonar_cxx_version')}"])

      - name: Show tags
        run: echo ${{ steps.version_tags.outputs.tags }}

      - name: Build and push image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sonar-cxx
          tags: ${{ steps.version_tags.outputs.tags }}
          registry: ghcr.io
          dockerfile: Dockerfile
          directory: .
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
